name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is env 
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - pro
          - staging


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Code 
        run: echo "code building"
    
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Building code
        run: echo "code built"
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: echo "code tasted"
        
  doploy:
    if: inputs.environment == 'pro'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "congratulation your app has been deployed"
    
  
